name: 'FFmpeg Distro Config'
description: 'Setup distribution specific configuration pieces'
inputs:
  github_tag:
    description: 'FFmpeg version from checked out source'
    required: true
  build_type:
    description: 'Build type of included libraries'
    required: true
  link_type:
    description: 'Link type of libraries'
    required: true
  msystem:
    description: 'MSYS Environment'
    required: true
  msys_path:
    description: 'Relative path of MSYS Environment'
    required: true
  arch:
    description: 'CPU Architecture'
    required: true
  build_config:
    description: 'FFmpeg Baseline Configuration'
    required: true
outputs:
  output_path:
    description: 'Add bits to FFmpeg config setup'
    value: ${{ steps.output-path.outputs.output_path }}
  build_file_ref:
    description: 'Filename of readme file included with generated build archive'
    value: ${{ steps.build-file-ref.outputs.build_file_ref }}
  version_name:
    description: 'Version header string'
    value: ${{ steps.version-name.outputs.version_name }}
  path_msys_include:
    description: "MSYS Path to lib includes"
    value: ${{ steps.path-msys-include.outputs.path_msys_include }}
  build_config:
    description: 'Updated build configuration'
    value: ${{ steps.build-config.outputs.build_config }}

runs:
  using: "composite"
  steps:
    - name: Include path
      id: 'path-msys-include'
      shell: bash
      run: |
        echo "Make a path string for using as include"
        msys_path="${{ inputs.msys_path }}"
        msys_path="${msys_path//\\//}"
        include_path="/${msys_path//:}/${{ inputs.msystem }}/include"
        include_path="${include_path,,}"
        echo "path_msys_include: $include_path"
        echo "path_msys_include=${include_path}" >> $GITHUB_OUTPUT
    - name: Build output path
      id: 'output-path'
      shell: bash
      run: |
        echo "Define path for build output (prefix)"
        path=$(pwd)
        path="${path}/builds/ffmpeg-${{ inputs.link_type }}"
        echo "output_path: $path"
        echo "output_path=${path}" >> $GITHUB_OUTPUT
    - name: Make version name string
      id: 'version-name'
      shell: bash
      run: |
        shopt -s extglob
        echo "Make a version name string for headers and arcbive file naming"
        cpu="arm64"
        if [[ ${{ inputs.msystem }} == "CLANG64" ]]; then
          cpu="x64"
        fi
        version_string="${{ inputs.github_tag }}"
        version_string="${version_string##+([[:alpha:]])}"
        version_name="ffmpeg-$version_string-${{ inputs.build_type }}-${{ inputs.link_type }}-win-${cpu}"
        echo "version_name: $version_name"
        echo "version_name=${version_name}" >> $GITHUB_OUTPUT
    - name: Make readme.txt filename
      id: 'build-file-ref'
      shell: bash
      run: |
        build_file_ref="${{ inputs.build_type}}-${{ inputs.link_type }}.txt"
        echo "build_file_ref: $build_file_ref"
        echo "build_file_ref=${build_file_ref}" >> $GITHUB_OUTPUT
    - name: Echo a config settings
      id: 'build-config'
      shell: bash
      run: |
        Echo "Update FFmpeg build config with distribution specific settings"
        temp_config="${{ inputs.build_config }}"
        temp_config+=" --prefix=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}"
        temp_config+=" --datadir=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}/presets"
        temp_config+=" --docdir=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}/docs"
        temp_config+=" --libdir=${{ steps.output-path.outputs.output_path }}/dump/libs"
        temp_config+=" --incdir=${{ steps.output-path.outputs.output_path }}/dump/include"
        temp_config+=" --extra-cflags=-I${{ steps.path-msys-include.outputs.path_msys_include }}"
        echo "temp_config: $temp_config"
        echo "build_config=${temp_config}" >> $GITHUB_OUTPUT
