name: 'FFmpeg Configuration Bits'
description: 'Add bits to FFmpeg config setup'
inputs:
  version:
    description: 'FFmpeg version from checked out source'
    required: true
  build_type:
    description: 'Build type of included libraries'
    required: true
  link_type:
    description: 'Link type of libraries'
    required: true
  msystem:
    description: 'MSYS Environment'
    required: true
  msys_path:
    description: 'Relative path of MSYS Environment'
    required: true
  arch:
    description: 'CPU Architecture'
    required: true
  ffmpeg_config:
    description: 'FFmpeg Baseline Configuration'
    required: true
outputs:
  output_path:
    description: 'Add bits to FFmpeg config setup'
    value: ${{ steps.step2.outputs.random-number }}
  build_file_ref:
    description: 'Filename of readme file included with generated build archive'
    value: ${{ steps.step2.outputs.random-number }}
  version_name:
    description: 'Version header string'
    value: ${{ steps.step2.outputs.random-number }}
  build_config:
    description: 'Updated build configuration'
    value: ${{ steps.build-config.outputs.build_config }}

runs:
  using: "composite"
  steps:
    - name: Edit MSYS include path
      shell: bash
      run: |
        echo "Start Edit MSYS include path"
        echo ${GITHUB_WORKSPACE}
        path=$(pwd)
        msystem=${{ inputs.msystem }}
        msystem=${${{ inputs.msystem }},,}
        msys_path="${{ inputs.msys_path }}"
        msys_path="${msys_path//\\//}"
        include_path="/${msys_path//:}"
        # echo "$msystem"
        # echo $msystem
        # echo $include_path
        # echo "$include_path"
        # echo "$msys_path"
        echo $msys_path
        echo "End Edit MSYS include path"
    - name: Echo a config settings
      id: 'version-name'
      shell: bash
      run: |
        echo "version" "${{ inputs.version }}"
        echo "build_type" ${{ inputs.build_type }}
        echo "link_type" ${{ inputs.link_type }}
        echo "msys_path" ${{ inputs.msys_path }}
        echo "arch" ${{ inputs.arch }}
        echo "ffmpeg_config" ${{ inputs.ffmpeg_config }}
    - name: Echo a config settings
      id: 'build-config'
      shell: bash
      run: |
        echo "ffmpeg_config ============"
        echo "$inputs.ffmpeg_config"
        # --prefix=$output_path/$version_name
        # --datadir=$output_path/$version_name/presets
        # --docdir=$output_path/$version_name/docs
        # --libdir=$output_path/dump/libs
        # --incdir=$output_path/dump/include 
        # --extra-cflags=-I/d/msys64/clangarm64/include
        echo "build_config=${temp_build_config}" >> $GITHUB_OUTPUT


# output_path="${path_base}/ffmpeg-${link_type}"
# build_file_ref="$build_type-${link_type}.txt"
# version_name="ffmpeg-$version-$build_type-$link_type-win-arm64"

# --prefix=$output_path/$version_name
# --datadir=$output_path/$version_name/presets
# --docdir=$output_path/$version_name/docs
# --libdir=$output_path/dump/libs
# --incdir=$output_path/dump/include 
# --extra-cflags=-I/d/msys64/clangarm64/include


# --prefix=/d/builds/ffmpeg-static/ffmpeg-8.0.1-full-static-win-arm64
# --datadir=/d/builds/ffmpeg-static/ffmpeg-8.0.1-full-static-win-arm64/presets
# --docdir=/d/builds/ffmpeg-static/ffmpeg-8.0.1-full-static-win-arm64/docs
# --libdir=/d/builds/ffmpeg-static/dump/libs
# --incdir=/d/builds/ffmpeg-static/dump/include
# --extra-cflags=-I/d/msys64/clangarm64/include
# --extra-ldflags='-Wl,--allow-multiple-definition'
